name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Run multistep dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: interdiscount/googleanalytics_exporter/googleanalytics_exporter
          tag_with_sha: true
